import { CONFIG } from './config.js';
const $=id=>document.getElementById(id); const state={token:null,busy:false};
async function api(url,opt={},timeout=300000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...opt,signal:c.signal,cache:'no-store'}),x=await r.text();let b={};try{b=x?JSON.parse(x):{}}catch{b={detail:x}}if(!r.ok)throw new Error(b.detail||b.message||`HTTP ${r.status}`);return b}finally{clearTimeout(t)}}
function busy(v){state.busy=v;$('inspectImportButton').disabled=v;$('executeImportButton').disabled=v||!state.token||!$('importConfirm').checked;$('importProgress').hidden=!v}
function result(v,e=false){const n=$('importResult');n.hidden=false;n.classList.toggle('error',e);n.textContent=typeof v==='string'?v:JSON.stringify(v,null,2)}
function reset(){state.token=null;$('importInspection').hidden=true;$('importResult').hidden=true;$('importConfirm').checked=false;$('executeImportButton').disabled=true}
export function initializeImport(done=()=>{}){const cfg=CONFIG.dataImport,m=$('importModal'),target=$('importTarget');if(!cfg?.enabled)return;for(const x of cfg.targets){const o=document.createElement('option');o.value=x.key;o.textContent=x.label;target.append(o)}$('importMode').value=cfg.defaultMode||'replace';const close=()=>{if(!state.busy)m.hidden=true};$('importButton').onclick=()=>{reset();m.hidden=false};$('closeImportDialogButton').onclick=close;m.querySelectorAll('[data-import-close]').forEach(x=>x.onclick=close);$('importFile').onchange=reset;target.onchange=reset;$('importConfirm').onchange=()=>busy(false);
$('inspectImportButton').onclick=async()=>{const f=$('importFile').files?.[0];if(!f)return result('Select a .gpkg file.',true);if(!f.name.toLowerCase().endsWith('.gpkg'))return result('Only .gpkg is accepted.',true);if(f.size>cfg.maxFileSizeMb*1024*1024)return result(`Maximum size is ${cfg.maxFileSizeMb} MB.`,true);reset();busy(true);try{const fd=new FormData();fd.append('file',f);const r=await api(`${cfg.apiBaseUrl}/inspect`,{method:'POST',body:fd},120000);state.token=r.upload_token;const dl=$('importInspectionDetails');dl.replaceChildren();for(const [k,v] of [['File',r.file_name],['Size',`${(r.file_size/1048576).toFixed(2)} MB`],['Layers',r.layers.length],['Expires',r.expires_at]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;dl.append(dt,dd)}const s=$('importSourceLayer');s.replaceChildren();for(const l of r.layers){const o=document.createElement('option');o.value=l.name;o.textContent=`${l.name} — ${l.feature_count??'?'} features · ${l.geometry_type||'Unknown'} · ${l.srs||'SRS unknown'}`;s.append(o)}$('importInspection').hidden=false;result('Inspection completed. Review the result before execution.')}catch(e){result(e.message,true)}finally{busy(false)}};
$('executeImportButton').onclick=async()=>{const mode=$('importMode').value,source=$('importSourceLayer').value,key=target.value;if(!confirm(`${mode.toUpperCase()} ${target.selectedOptions[0].textContent}?\nSource: ${source}\n\nThis updates PostGIS.`))return;busy(true);try{const r=await api(`${cfg.apiBaseUrl}/execute`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({upload_token:state.token,target:key,source_layer:source,mode})});result(r);await done(r)}catch(e){result(e.message,true)}finally{busy(false)}}}
